AxisCommunications/practical-react-components

- .github/workflows/verify.yml
We had some issues with Chrome on the older Ubuntu (at least when
running in headless mode). This steps up the Ubuntu version to 20.04 and
runs the browsers in the default headed mode.
> ci: newer ubuntu, run default headed

- .github/workflows/verify.yml
- sbin/commitlint.sh
Change commitlint to work on ranges, and update the Github workflow to
send in the merge requests `<base>..<head>` as the range.
> ci: fix commitlint workflow

- .github/workflows/verify.yml
As soon as new changes are pushed to `main` branch deploy new version of docs to Gihub pages (docs) branch
> ci: deploy new docs on merge to `main` branch

- packages/docs/src/mdx/coreComponents/Select.mdx
- Fixed a typo
- Updated "Filled variant (with check icon)" example to include the check from the start
> docs: minor Select improvements

- packages/docs/src/index.tsx
Changes the width of the docs content from 900px to 1200px. This improves the readability of the different playgrounds.
900px
1200px
> docs: change width of docs content

- .yarn/versions/97a94915.yml
- packages/core/src/Input/__snapshots__/index.test.tsx.snap
- packages/core/src/Paper/index.tsx
- packages/core/src/Select/BaseSelect.tsx
- packages/core/src/Select/BaseSelectSelector.tsx
- packages/core/src/Select/__snapshots__/MultiSelect.test.tsx.snap
- packages/core/src/Select/__snapshots__/SearchSelect.test.tsx.snap
- packages/core/src/Select/__snapshots__/Select.test.tsx.snap
- packages/core/src/Select/index.ts
- packages/ui-tests/src/coreComponents/Select.spec.ts
The selector itself could be reused to make other types of selects such
as a larger area, or a grid of things. This splits out the selector part
from BaseSelect into BaseSelectSelector.
In addition this adds a forwardRef to Paper so it can be reused in
dropdowns.
> refactor: split out selector from base select

- packages/docs/src/mdx/coreComponents/Tab.mdx
The tab example wasn't very clear, so I added a bit more real world example feel to it.
Before
After
Fixes #23.
> docs: improve Tab component example

- packages/core/src/Card/CardHeader.tsx
- packages/docs/src/mdx/coreComponents/Card.mdx
- packages/ui-tests/src/coreComponents/Card.cypress.tsx
BEAKING CHANGE:
- Refactors the `CardHeader` to use only `ReactNode` in order
to allow easier placement of the content without the need
for many confusing props.
- Adds `CardHeaderTypography` component for the header text
- Adds `CardSubHeaderTypography` component for the
subheader text
- Adds examples in `.mdx` files for how to implelement
previous examples
> feat(card)!: refactors `CardHeader` to use only `ReactNode`

- packages/core/src/Toast/index.ts
- packages/core/src/Toast/toastCreators.tsx
To easier create custom toasts we need to export the lower level components that are used for the
predefined toasts.
> feat(toasts): export lower level toast components

- packages/docs/src/Licenses.tsx
The GitHub pages for practical-react-components is served from a folder,
so the path to the licenses.txt file needs to be relative.
> fix(docs): use relative licenses.txt path

- packages/core/src/Icon/index.tsx
- packages/core/src/Menu/BaseMenu.tsx
- packages/core/src/Menu/Menu.tsx
- packages/core/src/Menu/__snapshots__/index.test.tsx.snap
BREAKING CHANGE:
- Refactors `BaseMenu` to use `ReactNode instead of `icon` prop
to allow customization of the menu button.
- Adds `MenuButtonIconContainer` and exports `MenuButtonIcon` and
`MenuButtonHalo` in order to create icon button component as before.
> feat(basemenu)!: refactors `BaseMenu` to use `ReactNode` for menu button

- packages/core/src/Select/BaseSelect.tsx
When refactoring the Select the call to the onBlur prop was accidentally removed. This restores that call which makes onBlur work as expected again for the select component.
> fix(select): call onBlur prop on blur

- packages/formik/src/FormikCheckboxGroup.tsx
- packages/formik/src/FormikRadioButtonGroup.tsx
The core components for RadioButtonGroup supports a generic to narrow
the values (e.g. using an enum). All Formik components should also
support this, but it was missing from the FormikRadioButtonGroup.
In addition the FormikCheckboxGroupField also supports the same generic
constructions as the base FormikCheckboxGroup.
> feat(formik): add generics to checkbox and radio button groups

- packages/core/src/Menu/Menu.tsx
Forgot to omit `button` prop from Menu when I refactored `BaseMenu`. Menu shouldn't have `button` prop.
> fix(menu): omit `button` prop from Menu

- packages/core/src/Menu/BaseMenu.tsx
- packages/core/src/Menu/__snapshots__/index.test.tsx.snap
- packages/docs/src/mdx/coreComponents/Menu.mdx
Export `MenuButton` again. `MenuButton` should be exported but
it was accidentally removed when refactoring `BaseMenu`.
Also added example in docs.
And fixed menu button that jumps when changing state
by adding `box-sizing: border-box`.
> fix(menu): export `MenuButton` and menu button jumps

- packages/core/src/Dialog/Dialog.tsx
- packages/core/src/Toast/toastCreators.tsx
- packages/core/src/utils/index.ts
- packages/core/src/utils/twoLinesClamp.ts
> feat(toast): support two lines label in Toast

- packages/core/src/Input/__snapshots__/index.test.tsx.snap
- packages/core/src/Select/BaseSelectSelector.tsx
- packages/core/src/Select/__snapshots__/MultiSelect.test.tsx.snap
- packages/core/src/Select/__snapshots__/SearchSelect.test.tsx.snap
- packages/core/src/Select/__snapshots__/Select.test.tsx.snap
When doing custom selects with svgs inside the selectors they are styled in the same color as the arrow which is probably not what the user wants.
> fix(select): only style select arrow, not all svgs

- packages/core/src/SimpleTable/__snapshots__/index.test.tsx.snap
- packages/core/src/SimpleTable/index.tsx
Limit transition property in order to avoid to move some component on hover.
> fix(simpletable): limit transition property

- packages/core/src/Chip/__snapshots__/index.test.tsx.snap
- packages/core/src/Chip/index.tsx
- packages/core/src/Select/__snapshots__/MultiSelect.test.tsx.snap
Icon in Chip component shouldn't shrink even if there is not enough space.
Also change icon color to darker color.
|Before |After |
|---|---|
|![chip-before](https://user-images.githubusercontent.com/24866179/110767409-867bf100-8256-11eb-97ac-be458b07f88b.png) |  ![chip-after](https://user-images.githubusercontent.com/24866179/110767426-8aa80e80-8256-11eb-9bf4-1e38fd312fea.png)|
> fix(chip): prevent to shrink icon in Chip

- package.json
"dev:icons" script doesn't work because of missing "build:icons".
> chore: enable "dev:icons" script

- packages/docs/src/mdx/coreComponents/Card.mdx
Found wrong example in docs and fixed it.
|Before |After |
|--|--|
| ![before-card](https://user-images.githubusercontent.com/24866179/113154838-b6f0f280-9238-11eb-9f18-9cb5d192973b.png)|![after-card](https://user-images.githubusercontent.com/24866179/113154858-bb1d1000-9238-11eb-98df-945e68b9dc5f.png)|
> fix(docs): CardHeader in Basic usage in docs

- packages/core/src/Menu/BaseMenu.tsx
- packages/ui-tests/src/coreComponents/Menu.spec.ts
Correctly close the menu when open when clicking on the menu button
again. Fixes #48.
> fix(menu): close when click on menu button

- packages/docs/src/mdx/coreComponents/Table.mdx
Instead of #74 , opened this pull request.
> feat(docs): add explanation for usage of both clickable row and menu inTable

- packages/core/src/Tooltip/index.tsx
|Before |After |
|--|--|
|![before](https://user-images.githubusercontent.com/24866179/117266575-afcf8c80-ae55-11eb-818b-658e8cb10676.png)| ![after](https://user-images.githubusercontent.com/24866179/117266603-b3fbaa00-ae55-11eb-993f-847477ebc419.png)|
> fix(tooltip): tooltip is cut when overflow horizontally

- packages/docs/src/mdx/coreComponents/Expandable.mdx
- packages/docs/src/mdx/coreComponents/Modal.mdx
- packages/docs/src/mdx/coreComponents/SearchSelect.mdx
- packages/docs/src/mdx/coreComponents/SelectList.mdx
- Code added in `Expandable.mdx` file. Fixes #93 
- `state` in `SearchSelect` example code initialized as a string. Fixes #95
- Change `value` of example code in `SelectList`. Fixes #96 
- Changed example code in `Modal` documentation with correct prop `title` and  use `useState` instead of `useBoolean`. Fixes #97
> Several small issues related to documentation fixed

- packages/docs/src/mdx/coreComponents/Card.mdx
I changed some `props` from `Card`  documentation  example code in order to have the correct code in the example. Fixes #98
I also added states to `Switch` and `TextInputField` components to give a little more interaction to the Demo:
https://user-images.githubusercontent.com/67017215/121399509-c8e8c300-c956-11eb-914c-8be7295381fd.mp4
> fix(docs): Card example code corrected

- packages/core/src/Tooltip/index.tsx
Also make the title optional for usage without title.
| |Before |After |
|--|--|--|
|only title |![only-header-before](https://user-images.githubusercontent.com/24866179/125048575-5deaf300-e0a0-11eb-8402-5d121ca3648d.png)| ![only-header-after](https://user-images.githubusercontent.com/24866179/125048591-617e7a00-e0a0-11eb-834f-7c8f35310f03.png)|
|only content |![only-content-before](https://user-images.githubusercontent.com/24866179/125048637-69d6b500-e0a0-11eb-87ef-a06418a3e595.png) |![only-content-after](https://user-images.githubusercontent.com/24866179/125048646-6d6a3c00-e0a0-11eb-94d7-dd8e4572fc94.png) |
> fix(tooltip): place title vertically in the middle when using only title

- packages/docs/src/Header.tsx
- packages/docs/src/context.tsx
- packages/docs/src/mdx/Code.tsx
Adds all 18 missing themes to the documentation page so that a user can see what's available by default.
> docs: add ALL themes to docs page

- packages/core/src/ExpandableList/ExpandableListItem.tsx
- packages/core/src/ExpandableList/ListItemContainer.tsx
- packages/core/src/ExpandableList/index.tsx
- packages/docs/src/mdx/coreComponents/ExpandableList.mdx
- Adds a new `accordion` property to the component in which only one item could be expanded.
- Use expanded tooltip for the cropped labels in the expandable list.
- Re-use `useHasOverflow` hooks from `react-hooks-shareable`.
> Accordion expandable list

- packages/core/src/ExpandableList/ExpandableListItem.tsx
- packages/core/src/ExpandableList/index.tsx
Make `accordion` property optional for the `ExpandableListItem` component.
> fix(expandableList): make `accordion` property optional

- packages/core/src/Dialog/Dialog.tsx
Correctly wrap components' content by placing all the content inside `DialogContent`.
> fix(dialog): correctly wrap components' content

- packages/core/src/ExpandableList/ListItemContainer.tsx
If expandable list is hidden by default than all the items get tooltips as the `useHasOverflow` will detect that the text for all the items is not completely shown so by using `useHasOverflowWithResizeEvent` the check will run on each resize which will resolve this issue.
> fix(expandableList): use `useHasOverflowWithResizeEvent` hook for text

- packages/core/src/Toast/Toast.tsx
Correctly wraps toast label if label is a long word eg
`thisisareallylongwordthatneedstobeclampedandwrappedwithanelipsis`
> fix(toast): correctly wrap label if word

- packages/core/src/Slider/Tick.tsx
Introduces a fix that aligns minimum and maximum labels left and right.
> fix(slider): align min and max tick labels

- packages/docs/src/index.tsx
- packages/docs/src/mdx/coreComponents/colorSelector.mdx
- packages/docs/src/mdx/themeCreator/ColorPicker.tsx
- packages/docs/src/mdx/themeCreator/ThemeCreator.tsx
With Theme-Creator you can generate a `THEME`  file with custom colors by changing the color of the 'slots'.
(All the colors from `Palette` are eligible)
Change a 'slot' color by clicking on the color segment and choosing a color from the Color-Picker.
https://user-images.githubusercontent.com/67017215/122547654-ac244d80-d030-11eb-9a44-42e330ca5c99.mp4
When the Preview has the desired look, download the file.
https://user-images.githubusercontent.com/67017215/122547770-d1b15700-d030-11eb-8b56-cbbf2395c012.mp4
Then just paste the `file` in the project and `import` it from its respective `path`, 
Example:
```tsx
import { myCustomTheme } from "./pathTo<downloadedFile>"
<PracticalProvider>
<ThemeProvider theme={myCustomTheme}>
<App />
</ThemeProvider>
</PracticalProvider>
``` …
> feat(docs): ThemeCreator

- packages/core/src/Slider/index.tsx
Limits the slider value to min and max values
> fix(slider): limit slider value

- packages/core/src/Table/ColumnResizerRow.tsx
- packages/core/src/Table/Table.tsx
- packages/core/src/Table/TableHeader.tsx
- packages/core/src/Table/TableRow.tsx
- packages/core/src/Table/__snapshots__/index.test.tsx.snap
- packages/core/src/Table/context.ts
Double clicking a divider resizes the two adjacent columns to fit their content.
Fixes #85
> feat(table): double-click resizes adjacent columns

- packages/core/src/Button/__snapshots__/index.test.tsx.snap
- packages/core/src/Button/index.tsx
- packages/core/src/DateTimePicker/__snapshots__/index.test.tsx.snap
- packages/core/src/FilePicker/__snapshots__/index.test.tsx.snap
- packages/core/src/Stepper/__snapshots__/index.test.tsx.snap
- packages/docs/src/mdx/coreComponents/Button.mdx
Fixed `<IconTextButton>` , Icon was overflown. Also added alignment to `<button>`.
Old behavior
Current behavior
Tested with `yarn link`
> fix(button): icon don't overflow and buttons are aligned

- packages/core/src/Select/SearchSelect.tsx
When user leaves the input, `isTyping` should be set to `false`.
Before:
After:
> fix(searchSelect): set isTyping to false on blur

- packages/docs/src/Menu.tsx
- packages/docs/src/types.ts
Adds a menu link to the github repository. Also adds the ability to use icons for the menu choices and adds icons for Home and
Changelog menu items.
> chore(docs): github repository link

- packages/core/src/Table/TableRow.tsx
Closes #138
|Before|After|
|--|--|
|![table-shadow_before](https://user-images.githubusercontent.com/24866179/144590303-3fc92fbf-bda5-4e3a-92a4-36b4bd886959.gif)| ![table-shadow_after](https://user-images.githubusercontent.com/24866179/144589373-4c309f3f-e277-4dae-8b42-64831bda0c6f.gif)|
> fix(table): hover effect does not stay on table row when menu on table row active

- packages/core/src/Practical.tsx
Export `DEFAULT_TOASTS_OPTIONS` so we can expose, use and override these in our project.
Example, in our project, we want to place the Toast vertically lower so they dont block certain items in our header. Use case would be something like this
`import { DEFAULT_TOASTS_OPTIONS } from 'practical-react-components-core'`
`const MY_PROJECT_TOASTS_OPTIONS = {
...DEFAULT_TOASTS_OPTIONS,
placement: { 
justify: {...DEFAULT_TOASTS_OPTIONS.placement.justify}, top: '30px' 
}
}`
> feat(toast): allow user to provide custom toastOptions 

- packages/core/src/Menu/BaseMenu.tsx
> fix(menu): prevent closing menu when you click an item that has a submenu

- packages/core/src/Select/MultiSelect.tsx
- packages/core/src/Select/__snapshots__/MultiSelect.test.tsx.snap
Apply `overflow: hidden` to the chips inside the multiselect so that it does not grow unnecessary and pushes its internal components outside the container.
Fixes: #195
> fix(select): apply overflow hidden to MultiSelect chips

- packages/core/src/Input/__snapshots__/index.test.tsx.snap
- packages/core/src/RadioButton/__snapshots__/index.test.tsx.snap
- packages/core/src/Slider/index.tsx
- packages/core/src/ToggleButtonGroup/__snapshots__/index.test.tsx.snap
- packages/core/src/utils/withField.tsx
Change opacity and disable pointer events for the `*Field` components label / unit label when the components are disabled.
Fixes: #193
> fix(utils): handle disabled label / unit label for `*Field` components

- packages/core/src/DraggableList/__snapshots__/index.test.tsx.snap
- packages/core/src/DraggableList/index.tsx
Moves drag handle inside `DraggableListItem` so it can be easily styled, for example, wrapped in the border.
No functionality or design changes.
Before:
After:
> refactor(draggable): moves drag handle inside `DraggableListItem`

- packages/docs/src/mdx/coreComponents/Slider.mdx
Add descriptive label to the demo slider using ticks without snap. Also change order so the optional `snap` is set to false last.
I refactored the code so the props did not contain a complex object `TickConfig` that the docs don't explain but reverted it.
> fix(docs): update slider docs

- packages/core/src/Tab/index.tsx
- packages/docs/src/mdx/coreComponents/Tab.mdx
Add `tabIndex` to the `Tab` component so it can be interacted with using the keyboard.
I tried to add the event key press for space key too but had some problems. Both with page scrolling down, without being able to prevent the event propagation and secondly also to correctly identifying the space key press. But now it's at least coherent with the left navigation that is tabbable and only interactive with the enter key and not the space key.
> feat(tab): make tabs interactive with keyboard

- packages/core/src/SelectList/__snapshots__/index.test.tsx.snap
- packages/core/src/SelectList/index.tsx
When the select list has focus, the key up and down key will change the
selected value instead of scrolling the list.
It would be good if the list would have some focus glow around it. But that's a task for a new commit.
> feat(selectList): change value with keyboard up/down

- packages/core/src/Chip/index.tsx
- packages/core/src/Select/MultiSelect.tsx
- packages/core/src/Select/__snapshots__/MultiSelect.test.tsx.snap
Add `Enter` key down event listeners on the remove icons. So that the control can be controlled with keyboard and not require a mouse.
> feat(multiSelect): remove selected options with keyboard

- packages/core/src/Toast/context.ts
- packages/core/src/Toast/toastCreators.tsx
Adds the option to remove close `button` from toast.  
We need to remove this button from some toast in ADA in order to avoid giving the user access to the interface while some processes are occurring.
> feat(toast): adds the option to remove the close button

- packages/core/src/Stepper/Step.tsx
- packages/core/src/Stepper/__snapshots__/index.test.tsx.snap
- packages/core/src/Stepper/index.test.tsx
- packages/core/src/Stepper/index.tsx
- packages/docs/src/mdx/coreComponents/Stepper.mdx
Add possibility to use custom component as a stepper label
- Fixes #217
> feat(stepper): allow component to stepper label

- packages/core/src/DateTimePicker/DateTimeInformation.tsx
- On some locales, hourCycle is being set to 'h24'
as default if hour12 is specified.
- Removes hour12 if it's false and adds hourCycle: 'h23'
- Fixes #221
> fix(dateTimePicker): display midnight as 00.XX

- packages/docs/src/mdx/coreComponents/Button.mdx
- packages/docs/src/mdx/coreComponents/Card.mdx
- packages/docs/src/mdx/coreComponents/Checkbox.mdx
- packages/docs/src/mdx/coreComponents/Dialog.mdx
- packages/docs/src/mdx/coreComponents/Divider.mdx
- packages/docs/src/mdx/coreComponents/DraggableList.mdx
- packages/docs/src/mdx/coreComponents/Input.mdx
- packages/docs/src/mdx/coreComponents/Menu.mdx
- packages/docs/src/mdx/coreComponents/RadioButton.mdx
- packages/docs/src/mdx/coreComponents/Select.mdx
- packages/docs/src/mdx/coreComponents/SelectNative.mdx
- packages/docs/src/mdx/coreComponents/SimpleTable.mdx
- packages/docs/src/mdx/coreComponents/Slider.mdx
- packages/docs/src/mdx/coreComponents/Switch.mdx
- packages/docs/src/mdx/coreComponents/Table.mdx
- packages/docs/src/mdx/coreComponents/TextArea.mdx
- packages/docs/src/mdx/coreComponents/Toast.mdx
- packages/docs/src/mdx/coreComponents/Typography.mdx
The stable / experimental icons in the docs menu no longer serves any purpose. Removing them.
> docs: remove stable/experimental icons from menu

- packages/core/src/designparams.ts
Exports all designparams as const for easier hinting of what's included in `spacing`, `componentSize` etc.
> chore: export designparams as const

- packages/core/src/Tooltip/index.tsx
Using pointerdown event instead of click
and toggle only if pointerType is not `mouse`
Co-authored-by: Mauricio Espinoza <Mauricio.Espinoza@axis.com>
Co-authored-by: Victor Ingvarsson <Victor.Ingvarsson@axis.com>
- Fixes #232
> fix(tooltip): use pointerdown event for touch

- packages/core/src/Dialog/BaseDialog.tsx
Adds max-width to dialogs so that they doe not overflow if viewed
on a small screen, such as on a moblie device
It is 1 row added so there is not much to summarize. The context is a use case within AXIS Device Assistant (ADA), configuring a connection to a wireless network. Unlike most use cases in ADA this is meant to be done on a mobile device. At the end of the process there is a confirmation dialog and with the current code it overflows such that . See attached images
> fix(dialog): make dialogs fit on small screens

- packages/core/src/Input/Input.tsx
If attribute step is specified, show base values
together with decimals.
By default a number input element is displaying integers without decimals when step is specified. To improve user experience and make it more clear that the input contains decimal values, show integers with the amount of decimals specified in the step attribute.
- Fixes #237
> feat(input): show decimals if step is defined

- packages/core/src/Tab/index.tsx
- packages/docs/src/mdx/coreComponents/Tab.mdx
- packages/ui-tests/src/coreComponents/Tab.cypress.tsx
- packages/ui-tests/src/coreComponents/Tab.spec.ts
Add a new Tabs and VerticalTabs (plural) component and removes the Tab and VerticalTab components. I does not make sense to give the user the ability to use Tabs individually, so instead we created a wrapper component which takes the tabs as options instead.
This will also make our PRC => Fluent conversion easier because Fluent has a wrapper component that handles all the clicking and switching logic.
BREAKING CHANGE: replaces Tab and VerticalTab components with Tabs and VerticalTabs components.
> feat(tabs)!: add tabs component

- packages/core/src/Toast/ToastsProvider.tsx
- packages/core/src/Toast/context.ts
- packages/core/src/Toast/index.ts
- packages/core/src/Toast/toastReducer.ts
- packages/core/src/Toast/useToasts.ts
Enables use of multiple ToastAnchors throughout the application sharing the toasts.
Moves the ToastMap to the ToastProvider
- Fixes #241
> feat(toast): use toasts from context

- packages/core/src/Progress/index.tsx
- packages/docs/src/mdx/coreComponents/Progress.mdx
Adds a "secondary" variant to the the progress. This will not break any existing usage of this component since the "primary" color will be default for the progress bar.
> feat: secondary progress

- packages/core/src/Button/index.tsx
- packages/core/src/Checkbox/__snapshots__/index.test.tsx.snap
- packages/core/src/Checkbox/index.tsx
- packages/core/src/Table/__snapshots__/index.test.tsx.snap
- packages/core/src/theme.ts
These colors will be used and customize in ADA
Border in `<Button>` and `<Checkbox>` are now using the new color slots with the same color as before, so it doesn't break anything.
> feat(theme): add more color slots

- packages/core/src/Transition/FoldTransition.tsx
Fix transition animation for expandable components in development.
Set only the initial offsetHeight of html elements for increaseHeight,
because in development when react runs in strict mode, the height of the component is set twice.
Also, create a [bug report](https://github.com/AxisCommunications/practical-react-components/issues/256)
> fix(transition): transition to expand component in development

- packages/core/src/RadioButton/RadioButton.tsx
- packages/core/src/RadioButton/__snapshots__/index.test.tsx.snap
- packages/docs/src/mdx/coreComponents/RadioButton.mdx
- packages/docs/src/mdx/formikComponents/FormikRadioButtonGroup.mdx
Added new property for setting columndirection
- [/] I have added tests that prove my fix is effective or that my feature works
- [/] I have commented my code, particularly in hard-to-understand areas
> feat(radiobutton): updated radiobutton with direction

- packages/core/src/Modal/index.tsx
Adding prop allowOutsideClick which is optional.
Default value is true, changing it to false stops the user from clicking outside the component, which stops the behavior of tabbing outside a component to be possible.
> feat(modal): allowoutsideclick optional prop

- packages/core/src/PopOver/index.tsx
- packages/core/src/Tooltip/index.tsx
- packages/core/src/Tooltip/utils/index.ts
- packages/core/src/Tooltip/utils/useTouchScrollDistance.ts
- packages/ui-tests/src/coreComponents/Tooltip.spec.ts
To give better user experience for phone and pad users, reposition popover on scroll event.
Also remove the tooltip when user, on a touch device, scrolled more than 150 pixels.
- Fixes #259
> Reposition popover on scroll & remove tooltip delayed from screen

- packages/core/src/Slider/index.tsx
We would like to build a custom slider with an indicator popup above the knob showing what the value of the slider is when pressed and when the knob is being moved.
This PR replaces this [PR 171](https://github.com/AxisCommunications/practical-react-components/pull/171) as we want to do the custom slider inside our project.
This PR adds two optional props `onPressed` and `onKnobMoved` that would allow us to archive this behavior in our project.
> feat(slider): adds `onPressed` and `onKnobMoved` props to allow for customization

- packages/core/src/Tooltip/index.tsx
Change 'white-space: nowrap' attribute to 'white-space: normal' in ExpandedTooltipTitle component CSS.
- Fixes [#264](https://github.com/AxisCommunications/practical-react-components/issues/264)
> fix(tooltip): wrap ExpandedTooltipTitle overflow

- packages/core/src/DraggableList/index.tsx
The key used by DraggableList should not change key depending on order.
- Fixes #269
> fix(core): segments missing while dragging

- packages/core/src/Tooltip/__snapshots__/index.test.tsx.snap
- packages/core/src/Tooltip/index.tsx
- packages/ui-tests/src/coreComponents/Tooltip.spec.ts
Fixes: #276
Imported useClickOutside from 'react-hooks-shareable' and added it to onPointerDown event.
- Fixes #276
> fix(tooltip): hide tooltip when touched outside of a component
