AxisCommunications/practical-react-components

packages/core/README.md
packages/formik/README.md
packages/icons/README.md

Adds basic README.md files for each package in monorepo.
Fixes: #7

docs: adds README.md for each package in monorepo

---

.gitignore
sbin/changelog.py

- fixed issue when no commits between tags
- added Python version check to start of script
- use python3 env (maybe not the most portable?)

fix: improve changelog script

---

sbin/changelog.py

Provide some better help descriptions, and use default latest tag with "single".

fix: better tag support for changelog

---

packages/core/src/Button/__snapshots__/index.test.tsx.snap
packages/core/src/Checkbox/__snapshots__/index.test.tsx.snap
packages/core/src/Chip/__snapshots__/index.test.tsx.snap
packages/core/src/DateTimePicker/__snapshots__/index.test.tsx.snap
packages/core/src/Droppable/__snapshots__/index.test.tsx.snap
packages/core/src/FilePicker/__snapshots__/index.test.tsx.snap
packages/core/src/Input/__snapshots__/index.test.tsx.snap
packages/core/src/Link/__snapshots__/index.test.tsx.snap
packages/core/src/Progress/__snapshots__/index.test.tsx.snap
packages/core/src/RadioButton/__snapshots__/index.test.tsx.snap
packages/core/src/Select/__snapshots__/MultiSelect.test.tsx.snap
packages/core/src/Select/__snapshots__/SearchSelect.test.tsx.snap
packages/core/src/Select/__snapshots__/Select.test.tsx.snap
packages/core/src/SelectList/__snapshots__/index.test.tsx.snap
packages/core/src/SelectNative/__snapshots__/index.test.tsx.snap
packages/core/src/Slider/__snapshots__/index.test.tsx.snap
packages/core/src/Spinner/__snapshots__/index.test.tsx.snap
packages/core/src/Stepper/__snapshots__/index.test.tsx.snap
packages/core/src/StrengthIndicator/__snapshots__/index.test.tsx.snap
packages/core/src/Switch/__snapshots__/index.test.tsx.snap
packages/core/src/Table/__snapshots__/index.test.tsx.snap
packages/core/src/TextArea/__snapshots__/index.test.tsx.snap
packages/core/src/ToggleButtonGroup/__snapshots__/index.test.tsx.snap
packages/core/src/color.ts
packages/core/src/theme.ts
packages/docs/src/mdx/coreComponents/colors.mdx
packages/docs/src/mdx/coreComponents/themes.mdx
packages/ui-tests/src/coreComponents/ToggleButtonGroup.cypress.tsx
packages/ui-tests/src/coreComponents/ToggleButtonGroup.spec.ts

Implements the material palette as a default palette and create a deep
purple theme to serve as an example in the documentation.

feat: richer palette and default theme

---

packages/core/src/Input/__snapshots__/index.test.tsx.snap
packages/core/src/Select/BaseSelectSelector.tsx
packages/core/src/Select/SearchSelect.tsx
packages/core/src/Select/__snapshots__/MultiSelect.test.tsx.snap
packages/core/src/Select/__snapshots__/SearchSelect.test.tsx.snap
packages/core/src/Select/__snapshots__/Select.test.tsx.snap
packages/docs/src/mdx/coreComponents/SearchSelect.mdx

- Shows the label of the selected value instead of the value
- Select all text on focus
- Revert to label for current value on blur
- Highlight the searched string in the option list so the user can identify why that option matched.
https://user-images.githubusercontent.com/182388/107019674-4088c480-67a2-11eb-93fa-6e63ec202de7.mp4

feat(searchselect): ux improvements

---

packages/docs/src/mdx/coreComponents/Toast.mdx

Shows a basic example of how you can create a toaster from scratch.

docs: add avanced toasts example

---

packages/icons/material-icons.json
packages/icons/src/hdmi.svg

feat(icons): add hdmi icon

---

packages/icons/material-icons.json
packages/icons/src/first-page.svg
packages/icons/src/last-page.svg

feat(icons): add first and last page icons

---

packages/icons/material-icons.json
packages/icons/src/user-add.svg

Added new icon based on the material icon.

feat(icons): add user-add icon

---

packages/icons/material-icons.json
packages/icons/src/mark-as-unread.svg
packages/icons/src/user-add.svg

Added a new icon based on Material icon.

feat(icons): add mark-as-unread icon

---

packages/icons/src/volume-high.svg
packages/icons/src/volume-low.svg
packages/icons/src/volume-medium.svg
packages/icons/src/volume-off.svg

Added icons for volume control.

feat(icons): add volume icons

---

packages/core/src/Slider/Tick.tsx
packages/core/src/Slider/__snapshots__/index.test.tsx.snap
packages/core/src/Slider/getXAbsolutePosition.ts
packages/core/src/Slider/index.tsx
packages/core/src/utils/withField.tsx
packages/docs/src/mdx/coreComponents/Slider.mdx

Introduces configuration for ticks in slider component. Passing an object with wanted values and labels and choose between snapping to closest value or not.

feat(slider): add slider with ticks

---

packages/icons/src/discovered-device.svg

feat(icons): add discovered-device icon

---

packages/core/src/Table/Table.tsx

Export `TableProps` interface.

feat(table): export `TableProps`

---

packages/icons/src/cancel.svg

feat(icons): add cancel icon

---

packages/icons/src/download.svg

Added:
to use on Theme documentation.

feat(icons): add download icon

---

packages/core/src/SelectNative/__snapshots__/index.test.tsx.snap
packages/core/src/SelectNative/index.tsx

fix(selectNative): icon is now clickable (#92)

---

packages/icons/src/audio-streaming.svg

feat(icons): add audio streaming icon

---

packages/core/src/Dialog/BaseDialog.tsx

Export components from the `BaseDialog` in order to be able to build the custom Dialogs

feat(dialog): export components from the `BaseDialog`

---

packages/icons/src/block.svg

feat(icons): adds block icon

---

packages/icons/src/speaker-group.svg

feat(icons): add speaker group icon

---

packages/icons/src/drag-indicator.svg

feat(icons): add drag indicator icon

---

packages/core/src/Tooltip/index.tsx

Exports the tooltip delay and animation for reuse in custom components.

feat: export tooltip delay time and animation

---

packages/core/src/Slider/Tick.tsx
packages/core/src/Slider/index.tsx

- Forwards disabled property from slider to tick labels.
- Changes tick label color

feat(slider): add disabled property to tick labels

---

packages/core/src/Droppable/__snapshots__/index.test.tsx.snap
packages/core/src/Droppable/index.tsx

- Add ability to tab into droppable.
- Add ability to select file using the enter key.

enhancement(droppable): ability to tab and select file with enter key

---

packages/core/src/Input/__snapshots__/index.test.tsx.snap
packages/core/src/Select/BaseSelect.tsx
packages/core/src/Select/BaseSelectSelector.tsx
packages/core/src/Select/__snapshots__/MultiSelect.test.tsx.snap
packages/core/src/Select/__snapshots__/SearchSelect.test.tsx.snap
packages/core/src/Select/__snapshots__/Select.test.tsx.snap
packages/docs/src/mdx/coreComponents/Select.mdx

- provide an upper bound max width for select popover if the label is very long.

fix(select): provide max width for select popover with long labels.

---

packages/core/src/SimpleTable/__snapshots__/index.test.tsx.snap
packages/core/src/SimpleTable/index.test.tsx
packages/core/src/SimpleTable/index.tsx
packages/docs/src/mdx/coreComponents/SimpleTable.mdx

Added an optional property `widths` to override default width by specified width with percentage.

fix(simpletable): unable to change column width

---

packages/core/src/Menu/BaseMenu.tsx
packages/core/src/Menu/__snapshots__/index.test.tsx.snap

| Before|After |
|--|--|
|![menu-button_before](https://user-images.githubusercontent.com/24866179/144405944-650f7fa3-25ae-42e5-8239-4ad2279afb3f.png) | ![menu-button_after](https://user-images.githubusercontent.com/24866179/144405991-870259fa-552b-42b5-b784-34be116e5851.png)|

fix(menu): hover effect does not stay on menu button when menu is activated

---

packages/icons/src/far-away.svg
packages/icons/src/manual-focus.svg

- add manual focus, near and far away icons

feat(icons): add manual focus and far away icons

---

packages/icons/src/arrow-back.svg

feat(icons): add arrow back icon

---

packages/icons/src/spot-focus.svg

feat(icons): add spot-focus icon

---

packages/icons/src/vertical-configuration.svg

feat(icons): add vertical configuration icon

---

packages/core/src/Menu/BaseMenu.tsx
packages/core/src/Menu/Menu.tsx
packages/core/src/Menu/__snapshots__/index.test.tsx.snap
packages/core/src/Menu/index.test.tsx
packages/docs/src/mdx/coreComponents/Menu.mdx
packages/ui-tests/src/coreComponents/Menu.cypress.tsx
packages/ui-tests/src/coreComponents/Menu.spec.ts

TODO:
- ~~[ ] Support multiple submenus in one menu~~ -> will be fixed in another PR

feat(menu): support submenu functionality

---

packages/core/src/Menu/BaseMenu.tsx
packages/core/src/Menu/__snapshots__/index.test.tsx.snap

Fixed lint and test error that occurred after merging submenu PR.

chore: fix lint and test error

---

packages/icons/src/logout.svg

feat(icons): add logout icon

---

packages/core/src/Dialog/Dialog.tsx
packages/core/src/Dialog/components/DialogFooterContent.tsx
packages/core/src/Dialog/components/DialogHeaderContent.tsx
packages/core/src/Dialog/components/DialogMainSection.tsx
packages/core/src/Dialog/components/index.ts
packages/core/src/Dialog/index.ts

Exports internal components to be able to build custom dialogs.

feat(dialog): export internal components

---

packages/core/src/Slider/index.tsx

When moving slider knob with keyboard keys and in a slider that has ticks that snap, change value on update to the closest tick instead of one percentage.

fix(slider): respect tick snap when changing value with keyboard

---

packages/core/src/utils/withField.tsx

Make all Label props optional as this was unintentionally changed when refactoring Label component.

fix(utils): make all Label props optional

---

packages/core/src/Tooltip/index.tsx

feat(tooltip): toggle tooltip on click
For devices using touchscreen, it is not possible to see a tooltip since pointerover and pointerout never fires.
Please include a summary of the change, a relevant motivation and context.
- Fixes #225

Support touch for tooltip

---

packages/core/src/Input/Input.tsx

This reverts commit 846092f126ba7d93bbaf219117723e0f5516d852.
This feature created issues and after a closer look it seems like a good idea to revert the changes.
- Fixes #243

Revert "feat(input): show decimals if step is defined"

---

packages/core/src/DateTimePicker/__snapshots__/index.test.tsx.snap
packages/core/src/DateTimePicker/index.test.tsx
packages/icons/src/copy-outline.svg
packages/icons/src/download-outline.svg
packages/icons/src/edit-outline.svg
packages/icons/src/link-outline.svg
packages/icons/src/preview-outline.svg
packages/icons/src/remove-circle-outline.svg
packages/icons/src/sync-outline.svg

Added new icons
- [ X ] I have verified that the code builds perfectly fine on my local system
- [ / ] I have added tests that prove my fix is effective or that my feature works
- [ / ] I have commented my code, particularly in hard-to-understand areas
- [ X ] I have verified that my code follows the style already available in the repository
- [ / ] I have made corresponding changes to the documentation

feat(icons): added new icons

---

packages/icons/src/alt-autofocus.svg

Add a new AltAutofocus icon.
- Fixes #261

feat(icons): implement new autofocus icon

---

packages/core/src/DraggableList/index.tsx

Fixes: #271
Check if a segment is locked before starting drag

fix(core): dragging locked segment

---

packages/core/src/Slider/__snapshots__/index.test.tsx.snap
packages/core/src/Slider/index.tsx

Add touch-action: none to container
- Fixes: #294

fix(slider): drag slider on small screen

---

packages/core/src/Input/Input.tsx

onFocus prop needs to be taken into account when handling focus
- Fixes #322

fix(input): add onFocus as prop to handleFocus
